name: pipeline-deployment

on:
  workflow_run:
    workflows:
      - pipeline-unit-tests
    branches:
      - main
    types:
      - completed

jobs:
  pipeline-deployment:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

      - name: Deploy to Google Cloud Functions
        uses: google-github-actions/deploy-cloud-functions@v3
        with:
          name: ${{ vars.GOOGLE_CLOUD_FUNCTION_NAME }}
          runtime: python312
          entry_point: pipeline
          source_dir: ./pipeline
          build_environment_variables: |-
            GOOGLE_FUNCTION_SOURCE=src/main.py
          environment_variables: |
            VERTEX_AI_LLAMA_MODEL=${{ vars.VERTEX_AI_LLAMA_MODEL }}
            BIGQUERY_DATASET_ID=${{ vars.BIGQUERY_DATASET_ID }}
            GOOGLE_STORAGE_BUCKET_NAME=${{ vars.GOOGLE_STORAGE_BUCKET_NAME }}
            PYTHONPATH=${{ env.PYTHONPATH }}:.