name: pipeline-unit-tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - 'ft/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install dependencies
        working-directory: ./pipeline
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -r requirements-test.txt

      - name: Run tests
        working-directory: ./pipeline
        run: |
          pytest test/unit --cov=src --cov-report=xml --cov-report=term-missing
